services:
  - type: web
    name: moex-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TINKOFF_API_TOKEN   # <-- добавляешь это
        sync: false
